### ISSUE TITLE
Wrong location on Mac Os

### ISSUE THREAD

**Issue by mensae** [league-of-legends-devs/feeder.lol-item-sets-generator.org#1]
Hello. 

First of all I want to thank you for your hard work. Secondly, I would like to report a huge bug.

I'm a Mac user. I've tried to use your application a couple of times in the last 2 months, but it seems like it doesn't work. Because i'm a computer scientists myself, i've done some further analysis in order to track down the problem. Apparently, the item sets are placed in the wrong directory of the League of Legends.app file...

I'll report here what I found out. 

Your application places the item sets (sub-categorizied in folders, one for each champion) in this directory: 

/Applications/League of Legends.app/Contents/LoL/Config/ItemSets/CHAMPNAME/ITEMSETNAME.json

But, in order to make it work, the correct location should be:

/Applications/League of Legends.app/Contents/LoL/Config/Champions/CHAMPNAME/Recommended/ITEMSETNAME.json

I hope you found this report useful.

If you need any other information, I'll be happy to collaborate.

Bye.

**Comment by Ilshidur** [comment]
Hello Enkkfull.

Thank you for this bug report, this is really appreciated !
I understand this bug and I am honestly very surprised that this has not been reported before.

The Mac application has its own repository : **[Ilshidur/LoL-item-sets-Mac](https://github.com/Ilshidur/LoL-item-sets-Mac)** and you should address this issue here as the main maintainer of this repo can be noticed about this.
(my bad, I gave the wrong link for bug reports [here](https://github.com/Ilshidur/lol-item-sets-generator.org), this is fixed).

I will close this issue and check if some users had the same bug. Thanks !
