### ISSUE TITLE
ProBuilds item sets are never available

### ISSUE THREAD

**Issue by jondmarien** [league-of-legends-devs/feeder.lol-item-sets-generator.org#2]
Like it says.

**Comment by Ilshidur** [comment]
Thanks for your report.

The problem is that the item sets are retrieved from the ProBuilds page, but the website has recently changed. So, the builder needs to be updated according to the new ProBuilds website.

I currently haven't much time to maintain the builder, but soon I will fix this issue and implement ProBuilds again :)

**Comment by Ilshidur** [comment]
**Fixed.**

**Comment by jondmarien** [comment]
Cool! Do I need to re-download from the website, or can I just refresh the item-sets?

**Comment by Ilshidur** [comment]
Only download the item sets. The builder changed, but not the application that downloads the sets from the builder. Happy playing !
